name: CI
on:
 push:
  branches: 
    - main
env:
  Deploy_Route_Url: ${{secrets.AWS_DEPLOY_DEV_ENV}}
  Lambda_Location: "backend/lambda/"
  region_to_deploy_lambdas: "ap-south-1"

jobs:
 build:
 
  runs-on: ubuntu-latest
  strategy: 
    matrix:
      go-version: [1.17]
  steps:
   - name: check the code
     uses: actions/Checkout@v2
    
   - name: Configure AWS Credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ${{secrets.AWS_DEFAULT_REGION}}

   - name: codebuild,Zip and Deploy    
     run: |
         funcname=listTop3ApprovedPos4
         echo "Checking if $funcname already exists"
         value=$(aws lambda list-functions --region ${{env.region_to_deploy_lambdas}} --query 'Functions[?starts_with(FunctionName, `$funcname`) == `true`].FunctionName'|grep funcname)
         echo $value
