name: CI
on:
 push:
  branches: 
    - main
  #paths:
    #- backend/lambda/**
env:
  Deploy_Route_Url: ${{secrets.AWS_DEPLOY_DEV_ENV}}

jobs:
 build:
 
  runs-on: ubuntu-latest
  strategy: 
    matrix:
      go-version: [1.17]
  steps:
   - name: check the code
     uses: actions/Checkout@v2
     
   - name: test
     run: echo "tested"
  
   
   - name: Get changed files
     id: files
     uses: jitterbit/get-changed-files@v1
     with:
       format: 'csv'

   - name: verify files
     run: |
       mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
       for added_modified_file in "${added_modified_files[@]}"; do
         echo "Do something with this ${added_modified_file}."
       done

  #  - name: setup go

  #    uses: actions/setup-go@v2
  #    with:
  #      go-version: ${{ matrix.go-version }}
  #    env:
  #     GO111MODULE: "on"
 
  #  - name: check setup
  #    run: |
     
  #      go mod init leapfrog-backend-Go-Lambdas
  #      go mod tidy

   - name: Commit details
     run: |
     
       echo ${{ github.event.head_commit.message }}
 
     
