name: CI
on:
 push:
  branches: 
    - main
  #paths:
    #- backend/lambda/**
env:
  Deploy_Route_Url: ${{secrets.AWS_DEPLOY_DEV_ENV}}

jobs:
 build:
 
  runs-on: ubuntu-latest
  strategy: 
    matrix:
      go-version: [1.17]
  steps:
   - name: check the code
     uses: actions/Checkout@v2
     
   - name: test
     run: echo "tested"
   - name: setup go

     uses: actions/setup-go@v2
     with:
       go-version: ${{ matrix.go-version }}
     env:
      GO111MODULE: "on"
 
   - name: check setup
     run: |
     
       go mod init leapfrog-backend-Go-Lambdas
       go mod tidy
 
   - name: check setup
     run: |
     
       echo ${{ github.event.head_commit.message }}
 
     
